"""Calls Sarvam's Document Intelligence Extract API and returns structured
fields, each with a confidence score and a source pointer.

This is the one file in the project that makes a model call. Everything
downstream (`sufficiency.py`, `audit.py`) only ever reads its output.

Built against `sarvamai==0.1.31` (the installed SDK's source, generated by
Fern from Sarvam's own OpenAPI spec) -- not just Sarvam's public docs, which
contradicted themselves on several details during research for this repo
(see README "What's verified vs. assumed"). As of this commit, no live
authenticated call has been made against these endpoints. The parsing in
`_to_extracted_document` follows the documented response shape
(`result` + `annotations`, each leaf carrying `confidence` and `sources`)
exactly, but the first live run may still surface surprises -- if it does,
this file is the place to fix, not paper over.

Known, documented limits worth remembering while reading this file:
- Source pointers are document + page only. There is no bounding box /
  region within the page for Extract results (Digitise has one; Extract
  does not).
- Handwriting support is only explicitly documented for Digitise, not for
  Extract. Whether Extract degrades gracefully on a handwritten field is
  untested here.
- 10-page hard cap per job; 10 requests/minute flat across all plan tiers.
"""

from __future__ import annotations

import json
import os
import time
from pathlib import Path
from typing import Any, Optional

from sarvamai import SarvamAI

from schema import DocumentType, ExtractedDocument, ExtractedField, SourcePointer

TERMINAL_STATUSES = {"completed", "partially_completed", "failed", "rejected"}
SUCCESS_STATUSES = {"completed", "partially_completed"}

MIME_TYPES = {
    ".pdf": "application/pdf",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
}

# One extraction schema per document type. Field names here are the
# normalized semantic names used throughout the rest of the project (see
# sufficiency.py's REQUIRED_FIELDS_BY_DOCUMENT) -- not necessarily the
# literal label printed on the document. The `description` is what steers
# Sarvam Vision to the right value; it doubles as documentation here.
DOCUMENT_SCHEMAS: dict[DocumentType, dict[str, Any]] = {
    DocumentType.DEATH_CERTIFICATE: {
        "type": "object",
        "properties": {
            "deceased_name": {"type": "string", "description": "Full name of the deceased as printed on the certificate"},
            "date_of_death": {"type": "string", "description": "Date of death as printed, e.g. DD-MM-YYYY"},
            "registration_number": {"type": "string", "description": "Death registration or certificate number"},
            "place_of_death": {"type": "string", "description": "Place of death as recorded (city/town)"},
            "issuing_authority": {"type": "string", "description": "Municipal body or authority that issued the certificate"},
        },
    },
    DocumentType.HOSPITAL_DISCHARGE_SUMMARY: {
        "type": "object",
        "properties": {
            "deceased_name": {"type": "string", "description": "Patient name as printed on the discharge summary"},
            "cause_of_death": {"type": "string", "description": "Cause of death as recorded by the hospital, including any handwritten notes"},
            "date_of_admission": {"type": "string", "description": "Date the patient was admitted, e.g. DD-MM-YYYY"},
            "hospital_name": {"type": "string", "description": "Name of the hospital that issued the summary"},
        },
    },
    DocumentType.CLAIM_INTIMATION_FORM: {
        "type": "object",
        "properties": {
            "deceased_name": {"type": "string", "description": "Name of the deceased life assured as entered on the form"},
            "claimant_name": {"type": "string", "description": "Name of the claimant/nominee as entered on the form"},
            "relationship_to_deceased": {"type": "string", "description": "Claimant's stated relationship to the deceased"},
            "policy_number": {"type": "string", "description": "Insurance policy number"},
            "date_of_death": {"type": "string", "description": "Date of death as entered on the form, e.g. DD-MM-YYYY"},
        },
    },
    DocumentType.NOMINEE_KYC: {
        "type": "object",
        "properties": {
            "claimant_name": {"type": "string", "description": "Full name as printed on the KYC document"},
            "id_type": {"type": "string", "description": "Type of ID document, e.g. Aadhaar, PAN, Voter ID, Passport"},
            "id_number": {"type": "string", "description": "ID number as printed on the document"},
        },
    },
}


class ExtractionError(Exception):
    """Raised when Sarvam can't be reached, rejects the job, or the job
    ends in a non-success terminal status. Never raised to mean "field not
    found" -- that's a normal `ExtractedField(found=False)`, not an error."""


class SarvamExtractor:
    def __init__(
        self,
        api_key: Optional[str] = None,
        poll_interval_seconds: float = 5.0,
        poll_timeout_seconds: float = 300.0,
    ):
        key = api_key or os.environ.get("SARVAM_API_KEY")
        if not key:
            raise ExtractionError(
                "SARVAM_API_KEY is not set. Copy .env.example to .env and add your key from https://dashboard.sarvam.ai"
            )
        self.client = SarvamAI(api_subscription_key=key)
        self.poll_interval_seconds = poll_interval_seconds
        self.poll_timeout_seconds = poll_timeout_seconds

    def extract_document(
        self, document_type: DocumentType, file_path: Path, language: str = "en-IN"
    ) -> ExtractedDocument:
        """Run one document through Sarvam's Extract API and return it as
        an ExtractedDocument with per-field confidence and source."""
        schema = DOCUMENT_SCHEMAS[document_type]
        mime_type = MIME_TYPES.get(file_path.suffix.lower())
        if mime_type is None:
            raise ExtractionError(f"Unsupported file type for Sarvam Extract: {file_path.suffix}")

        with file_path.open("rb") as f:
            job = self.client.doc_ai.extract(
                file=[(file_path.name, f, mime_type)],
                schema=json.dumps(schema),
                language=language,
                output_format="json",
            )

        status = self._poll_until_terminal(job.job_id)
        if status.status not in SUCCESS_STATUSES:
            raise ExtractionError(
                f"Sarvam extract job {job.job_id} for {file_path.name} ended with status={status.status!r}"
            )

        results = self.client.doc_ai.get_results(job_id=job.job_id)
        return self._to_extracted_document(document_type, file_path.name, results)

    def _poll_until_terminal(self, job_id: str):
        elapsed = 0.0
        while True:
            status = self.client.doc_ai.get_status(job_id=job_id)
            if status.status in TERMINAL_STATUSES:
                return status
            if elapsed >= self.poll_timeout_seconds:
                raise ExtractionError(f"Sarvam job {job_id} did not reach a terminal status within {self.poll_timeout_seconds}s")
            time.sleep(self.poll_interval_seconds)
            elapsed += self.poll_interval_seconds

    def _to_extracted_document(self, document_type: DocumentType, filename: str, results: Any) -> ExtractedDocument:
        document = ExtractedDocument(document_type=document_type, filename=filename)
        result: dict[str, Any] = getattr(results, "result", None) or {}
        annotations: dict[str, Any] = getattr(results, "annotations", None) or {}

        for field_name in DOCUMENT_SCHEMAS[document_type]["properties"]:
            value = result.get(field_name)
            found = value is not None and value != ""

            annotation = annotations.get(field_name) if isinstance(annotations, dict) else None
            confidence = 0.0
            source_pointer = None
            if isinstance(annotation, dict):
                confidence = float(annotation.get("confidence") or 0.0)
                sources = annotation.get("sources") or []
                if sources:
                    first_source = sources[0]
                    source_pointer = SourcePointer(
                        document_type=document_type,
                        filename=first_source.get("filename", filename),
                        page_num=first_source.get("page_num"),
                    )

            document.fields[field_name] = ExtractedField(
                field_name=field_name,
                value=value if found else None,
                confidence=confidence if found else 0.0,
                source=source_pointer,
                found=found,
            )

        return document
